version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"