spring:
  application:
    name: tasktracker

  # === DataSource (PostgreSQL in Docker) ===
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # === Hibernate / JPA ===
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
